version: "3"
services:
  web:
    image: jiayihu/letsbox-workshops:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4200:80"
    networks:
      - webnet
  mongo:
    image: mongo:4.0
    ports:
      - "27017:27017"
    volumes:
      - "/home/docker/data/db:/data/db"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    networks:
      - webnet
networks:
  webnet:
